website:
  title: "YWM-website"
  image: imgs/icon.png
  
  favicon: imgs/logo.png
  
  navbar:
    pinned: true
    logo: /imgs/logo2.png
    
    left:
      - text: "Exercises"
        href: exercises/index.qmd
      - text: "Labs"
        href: labs/index.qmd
      - text: "Homeworks"
        href: homeworks/index.qmd
    right:
      - icon: folder-symlink
        href: https://www.marvinschmitt.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com
      - icon: envelope
        aria-label: email
        href: "mailto:mail.marvinschmitt@gmail.com"  
  
  
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2024 Yang Weiming</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 8888
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - css/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
  ipynb: default


